name: pattern_lock
description:
  Pattern lock as Flutter widget. Customizable and easy to use.
version: 1.0.2
author: Alexander Zhdanov <qwert2603@mail.ru>
homepage: https://github.com/qwert2603/pattern_lock

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
